aaseurl      = "http://codecowboy.io"
title        = "Codecowboydotio"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Ramblings of a developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Technology blog for codecowboy.io"
  keywords = "homepage, blog, technology"
  images = [""]

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
          "Made with &#10084; by codecowboy"]

# Colors for favicons
#
[params.favicon.color]
  mask = "#1b1c1d"
  msapplication = "#1b1c1d"
  theme = "#1b1c1d"

[author]
  name = "codecowboy"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/codecowboydotio"

[[params.social]]
  name = "email"
  url  = "mailto:nobody@example.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/codecowboydotio"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/scottv1/"

[languages]
  [languages.en]
    title = "Codecowboy.io"
    subtitle = "Ramblings of a developer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "codecowboy.io"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"
